### ISSUE TITLE
is it still maintained ?

### ISSUE THREAD

**Issue by lorenzofox3** [peterruggero/postmaster-nodejs#5]
Hi, I was wondering whether this client library was "official" and whether is was still maintained ?

**Comment by CountZachula** [comment]
Hey @lorenzofox3,

Thanks for trying out Postmaster!

Yes, it is the official library. As for being maintained, the short answer is yes. The long answer is that since I don't work directly for Postmaster, any major revisions/updates are contingent upon a new contract. Anything minor I just go ahead and quickly fix. I'll always answer questions and offer guidance within reason.

I hope this answers your questions.

**Comment by lorenzofox3** [comment]
Thanks a lot !
